[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AdMD6EhNk6NSdVQY_EeOQ6Sm9nQok0_AzpnmE_s_76fAKRF4xC142AvMf5ozkTVybfj28nHsZx0Od9fxugwkJLAHLJlCKy4WyWuOqwKwNXRez7Ilf-iAzDnJHbZFlk6AwqMxZK1fR6tGEWKnnnwn4LQy1-wLsA_SrJyMeUAF7RER1yrhprX0vvjYCxYEXgosvLrnSJgaCgYKAfoSARUSFQHGX2Mie2RagifLf7Pa4uDXerJiEQ0206","token_type":"Bearer","refresh_token":"1//0hSdmsD5sqJFqCgYIARAAGBESNwF-L9Ir0_zohW1KejWSXYlNWsvTADhef95M7x07x03nvcdihubvP-mQrCj8KGyVwPZJdCDhPXY","expiry":"2026-08-23T23:34:57.671831261-03:00"}
team_drive = 
client_id = 115297000941-vge5q7tdnukgk6ts28kp9ss8boti6s86.apps.googleusercontent.com
client_secret = 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

